<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NIT-LPT-R0100" ignored="0" name="Android emulator1" tests="1" failures="1" timestamp="05 Jul 2019 08:48:32 GMT" time="25.228" errors="0">
  <testcase name="verify_loginfunctionality_for_valid_credentials" time="6.249" classname="com.appium.testcase.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.appium.testcase.LoginTest.verify_loginfunctionality_for_valid_credentials(LoginTest.java:34)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginfunctionality_for_valid_credentials -->
</testsuite> <!-- Android emulator1 -->
