<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NIT-LPT-R0100" ignored="0" name="Android emulator1" tests="1" failures="1" timestamp="11 Jul 2019 06:18:12 GMT" time="18.915" errors="0">
  <testcase name="Verify_Login_Functionality_For_Valid_credentials" time="4.236" classname="com.appium.testcase.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.appium.testcase.LoginTest.Verify_Login_Functionality_For_Valid_credentials(LoginTest.java:36)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Verify_Login_Functionality_For_Valid_credentials -->
</testsuite> <!-- Android emulator1 -->
